require("lspservers.lua-server")
require("lspservers.vim-server")
require("lspservers.kotlin-server")
require("lspservers.vue-server")
require("lspservers.json-server")
require("lspservers.graphql-server")
require("lspservers.ts-server")
require("lspservers.gradle-server")
